version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: present-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:5000
    networks:
      - present-network

  backend:
    build: ./backend
    container_name: present-backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/present
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - present-network

  db:
    image: postgres:14
    container_name: present-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=present
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - present-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  present-network:
    driver: bridge

volumes:
  postgres_data: 