version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-prod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-MiContraseñaSegura123}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-foco}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_prod_data:/data/db
      - ./mongodb_backup:/mongodb_backup
    networks:
      - app_network_prod

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend-prod
    restart: always
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - app_network_prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend-prod
    restart: always
    ports:
      - "3000:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app_network_prod

volumes:
  mongodb_prod_data:

networks:
  app_network_prod:
    driver: bridge
