version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-staging
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-present}
      ENVIRONMENT: staging
    volumes:
      - mongodb_staging_data:/data/db
    networks:
      - app_network_staging
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "mongodb-staging"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      args:
        - BUILD_ENV=staging
    image: present/backend:staging
    container_name: backend-staging
    restart: always
    ports:
      - "${BACKEND_PORT:-5001}:5000"
    env_file:
      - ./backend/.env.staging
    environment:
      - NODE_ENV=production
      - ENVIRONMENT=staging
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb-staging:27017/${MONGO_DB:-present}?authSource=admin
      - FRONTEND_URL=${FRONTEND_URL:-https://staging.present.attadia.com}
      - BACKEND_URL=${BACKEND_URL:-https://api.staging.present.attadia.com}
      - IS_STAGING=true
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app_network_staging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "backend-staging"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - BUILD_ENV=staging
    image: present/frontend:staging
    container_name: frontend-staging
    restart: always
    ports:
      - "${HTTP_PORT:-8080}:80"
    env_file:
      - ./frontend/.env.staging
    environment:
      - NODE_ENV=production
      - ENVIRONMENT=staging
      - VITE_API_URL=http://localhost:5001/api
      - VITE_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - IS_STAGING=true
    volumes:
      - ./nginx/conf.d/staging.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app_network_staging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "frontend-staging"

networks:
  app_network_staging:
    name: present_app_network_staging

volumes:
  mongodb_staging_data:
    name: present_mongodb_staging_data
