version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-prod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: present
    volumes:
      - /data/mongodb:/data/db
      - /data/backups:/data/backups
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend-prod
    restart: always
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/present?authSource=admin
      - CORS_ORIGINS=https://present.attadia.com
      - FRONTEND_URL=https://present.attadia.com
      - BACKEND_URL=https://api.present.attadia.com
      - PORT=5000
      - JWT_SECRET=un_secreto_jwt_muy_largo_y_seguro_123456789
      - REFRESH_TOKEN_SECRET=otro_secreto_refresh_muy_largo_y_seguro_987654321
      - SESSION_SECRET=un_secreto_session_muy_largo_y_seguro_456789123
      - GOOGLE_CLIENT_ID=21564026422-n684af8adp48dni8tuc2q2pqc8npb1r7.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=https://api.present.attadia.com/api/auth/google/callback
    volumes:
      - backend_logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend-prod
    restart: always
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
  backend_logs: 