version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-staging
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-present}
      ENVIRONMENT: staging
    volumes:
      - mongodb_staging_data:/data/db
    networks:
      - app_network_staging
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "mongodb-staging"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
      args:
        - BUILD_ENV=staging
    image: present/backend:staging
    container_name: backend-staging
    restart: always
    expose:
      - "5000"
    env_file:
      - ./backend/.env.staging
    environment:
      - NODE_ENV=production
      - ENVIRONMENT=staging
      - IS_STAGING=true
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb-staging:27017/${MONGO_DB}?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app_network_staging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "backend-staging"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - BUILD_ENV=staging
    image: present/frontend:staging
    container_name: frontend-staging
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./frontend/.env.staging
    environment:
      - NODE_ENV=production
      - ENVIRONMENT=staging
      - IS_STAGING=true
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot
    depends_on:
      - backend
    networks:
      - app_network_staging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "frontend-staging"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot-staging
    volumes:
      - ./ssl/certbot/conf:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot
    depends_on:
      - frontend
    command: certonly --webroot --webroot-path=/var/www/certbot --email admin@attadia.com --agree-tos --no-eff-email -d staging.present.attadia.com -d api.staging.present.attadia.com

networks:
  app_network_staging:
    name: present_app_network_staging

volumes:
  mongodb_staging_data:
    name: present_mongodb_staging_data
