/**
 * @deprecated Import from @shared/styles/hubSectionStyles. Aliases kept for ATTA consumers.
 */
export {
  HUB_SECTION,
  HUB_SECTION as ATTA_HUB,
  hubSectionBg,
  hubSectionBg as attaHubSectionBg,
  HUB_SECTION_CARD_BODY_MIN_HEIGHT,
  HUB_SECTION_CARD_BODY_MIN_HEIGHT as ATTA_HUB_CARD_BODY_MIN_HEIGHT,
  HUB_SECTION_CARD_MIN_HEIGHT,
  HUB_SECTION_CARD_MIN_HEIGHT as ATTA_HUB_CARD_MIN_HEIGHT,
  getHubCardSx,
  getHubSectionCardSx,
  getHubSectionCardSx as getAttaHubSectionCardSx,
  hubSectionShellSx,
  hubHeaderActionSx,
  hubSectionHeaderSx,
  hubSectionHeaderSx as attaHubSectionHeaderSx,
  hubSectionTitleSx,
  hubSectionBodySx,
  hubSectionBodySx as attaHubSectionBodySx,
  hubSectionShellBodySx,
  hubGridContainerSx,
  hubGridItemSx,
  HUB_SUBSECTION,
  HUB_SUBSECTION as ATTA_HUB_SUBSECTION,
  getHubSubsectionSx,
  getHubSubsectionSx as getAttaHubSubsectionSx,
  hubExpandButtonSx,
  hubHeaderIconSx,
} from '@shared/styles/hubSectionStyles';
