export { default as Register } from './Register.jsx';
export { default as Rutinas } from './Rutinas.jsx';
export { default as Inquilinos } from './Inquilinos.jsx';
export { default as Contratos } from './Contratos.jsx';

export { default as Transacciones } from './Transacciones.jsx';

export { default as Tareas } from './Tareas.jsx';
export { default as Salud } from './Salud.jsx';
export { default as Recurrente } from './Recurrente.jsx';
export { default as Proyectos } from './Proyectos.jsx';
export { default as Propiedades } from './Propiedades.jsx';
export { default as Perfil } from './Perfil.jsx';
export { default as Preferencias } from './Preferencias.jsx';
export { default as Monedas } from './Monedas.jsx';
export { default as MercadoPagoCallbackPage } from './MercadoPagoCallbackPage.jsx';
export { default as Login } from './Login.jsx';
export { default as Lab } from './Lab.jsx';
export { default as Inversiones } from './Inversiones.jsx';
export { default as Inventario } from './Inventario.jsx';
export { default as Habitaciones } from './Habitaciones.jsx';
export { default as Finanzas } from './Finanzas.jsx';
export { default as Dieta } from './Dieta.jsx';
export { default as Deudores } from './Deudores.jsx';
export { default as DataCorporal } from './DataCorporal.jsx';
export { default as Cuentas } from './Cuentas.jsx';
export { default as Configuracion } from './Configuracion.jsx';
export { default as Autos } from './Autos.jsx';
export { default as Archivo } from './Archivo.jsx'; 