export { default as PropiedadCard } from './PropiedadCard';
export { default as PropiedadForm } from './PropiedadForm';
export { default as PropiedadDetail } from './PropiedadDetail';
export { default as TipoPropiedadIcon } from './TipoPropiedadIcon';
export { default as HabitacionesForm } from './HabitacionesForm';
export { default as PropiedadContent, crearSeccionesPropiedad, SECTION_CONFIGS, SECTION_PADDING_X } from './PropiedadContent';
export * from './SeccionesPropiedad';
export * from './propiedadUtils';
export * from './PropiedadStyles';
export * as contratos from './contratos';
export * as inquilinos from './inquilinos'; 